language: rust
dist: trusty
sudo: true

os:
  - linux
  - osx
  - windows

rust:
  - stable

addons:
  apt:
    packages:
      - cmake
      - libgtk-3-dev
      - p7zip-full
  homebrew:
    packages:
    - p7zip

install:
  - rustup component add rustfmt
  - rustfmt -V

script:
  - cargo fmt --all -- --check
  - cargo test
  - cargo build --release
  - mkdir out
  - cp ./target/release/**/libui.dll ./target/release/**/libui.so ./out/
  - cp ./target/release/**/simple-menu.exe ./target/release/**/simple-menu ./out/
  - cd out
  - 7z a -t7z -m0=lzma -ms=on ../$TRAVIS_OS_NAME.7z *
  - cd ..
deploy:
  provider: releases
  # ⋮
  edge: true
  api_key: $GITHUB_TOKEN
  file_glob: true
  file: $TRAVIS_OS_NAME.7z
  skip_cleanup: true
  on:
    tags: true
