language: rust
dist: trusty
sudo: true

os:
  - linux
  - osx
  - windows

rust:
  - stable

addons:
  apt:
    packages:
      - cmake
      - libgtk-3-dev

install:
  - rustup component add rustfmt
  - rustfmt -V

script:
  - cargo fmt --all -- --check
  - cargo test
  - cargo build --release

deploy:
  provider: releases
  # ⋮
  edge: true
  api_key: $GITHUB_TOKEN
  file_glob: true
  file:
    - ./target/release/**/libui.dll
    - ./target/release/**/simple-menu.exe
    - ./target/release/**/libui.so
    - ./target/release/**/simple-menu
  skip_cleanup: true
  on:
    tags: true
