language: rust
dist: trusty
sudo: true

os:
  - linux
  - osx
  - windows

rust:
  - stable

addons:
  apt:
    packages:
      - cmake
      - libgtk-3-dev
      - p7zip-full
      - zsh
  homebrew:
    packages:
    - p7zip
    - zsh
install:
  - rustup component add rustfmt
  - rustfmt -V

script:
  - cargo fmt --all -- --check
  - cargo test
  - cargo build --release
  - cd ./target/release/
  - 7z a -t7z -m0=lzma -ms=on ../../$TRAVIS_OS_NAME.7z *
  - cd ..
  - cd ..
deploy:
  provider: releases
  # ⋮
  edge: true
  api_key: $GITHUB_TOKEN
  file_glob: true
  file: $TRAVIS_OS_NAME.7z
  skip_cleanup: true
  on:
    tags: true
